### ISSUE TITLE
Stops model hook from executing

### ISSUE THREAD

**Issue by RobbieTheWagner** [bttf/ember-scroll-operator#1]
Seems to make models not be defined anymore. Also, it doesn't seem to reset the scroll like it should anyway.

**Comment by bttf** [comment]
Could you post the route that you're including the mixin in? My suspicions lie with missing `_super` calls in necessary hooks

**Comment by RobbieTheWagner** [comment]
@bttf I am not using any of the hooks though. Just model and afterModel.

``` js
import Ember from 'ember';
const { inject: { service }, Route } = Ember;

export default Route.extend({
  headData: service(),
  model() {
    return {
      projectTypes: [
        {
          fieldName: 'oss',
          name: 'project-type',
          text: 'OSS'
        },
        {
          fieldName: 'training',
          name: 'project-type',
          text: 'Ember Training'
        },
        {
          fieldName: 'dev',
          name: 'project-type',
          text: 'Ember Development'
        }
      ]
    };
  },
  afterModel() {
    return this.get('headData').setProperties({
      title: 'Ship Shape - Contact',
      description: 'Contact us for Ember.js consulting work!',
      type: 'website',
      url: 'http://shipshape.io/contact'
    });
  }
});
```

**Comment by bttf** [comment]
Ah I see. And which mixin are you using? Did this start happening after upgrading to 0.0.4?

**Comment by RobbieTheWagner** [comment]
@bttf I am using `ScrollOperatorMixin`. I would like scrolling to behave as intended for the web, like the mixin implies it will do.

I had not used any previous versions. I just found this today.

**Comment by bttf** [comment]
@rwwagner90 could you try [v0.0.5](https://github.com/bttf/ember-scroll-operator/releases/tag/v0.0.5), should be fixed

**Comment by RobbieTheWagner** [comment]
@bttf the model hooks now execute, but it is never resetting my scroll position on link-to navigation to routes or saving the scroll position for routes I already visited. It's essentially doing nothing it appears.

**Comment by bttf** [comment]
@rwwagner90 Ah, stupid mistake. Try [v0.0.6](https://github.com/bttf/ember-scroll-operator/releases/tag/v0.0.6) please

**Comment by RobbieTheWagner** [comment]
@bttf still does not do anything 😢 . As I click links to go to other routes, it keeps my scroll position from previous routes, and it should be resetting it.

**Comment by RobbieTheWagner** [comment]
@bttf going to close this, as the model hooks run, and make a new issue
